services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      DOMAIN: "http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}"
    volumes:
      - vw-data:/data/
    networks:
      - ${TRAEFIK_NETWORK}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true" # Enable reverse proxy
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)" # Domain names to reach the app
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}" # Tell reverse proxy which port to use
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=Security" # Group for this service on the homepage
      - "homepage.name=vaultwarden" # Name of this service on the homepage
      - "homepage.icon=vaultwarden.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Password Manager" # Description of this service on the homepage
      - "nautical-backup.override-source-dir=${STACK_NAME}_vaultwarden"
      - "nautical-backup.additional-folders=${STACK_NAME}_vaultwarden"

volumes:
  vw-data:
